// photon/tests/m6/convergence_test.cpp
//
// The convergence check: same logical program in three forms (Photon
// .pho, Python @photon.kernel, C++ [[photon::kernel]]) produces the
// same compiled Spinor profile.
//
// The Python form is read from a fixture file recorded by running
// `photon/tests/corpus/convergence/<name>.py` directly (the script
// prints `bell.phonon_text`). The fixture is regenerated by tests
// when the engine extension is available; otherwise the fixture
// supplied in source is replayed (cassette-style).

#include "phonon/dialect/Phonon.h"
#include "photon/bindings/Engine.h"
#include "photon/cppfront/Ingest.h"
#include "photon/lang/Lower.h"
#include "photon/lang/Parser.h"
#include "test_main.h"

#include <fstream>
#include <sstream>
#include <string>

using photon::bindings::CompiledProgram;
using photon::bindings::ResourceEstimate;
namespace pl = photon::lang;
namespace pd = phonon::dialect;
namespace sd = spinor::dialect;

namespace {

std::string readFile(const std::string& p) {
  std::ifstream f(p);
  std::stringstream ss; ss << f.rdbuf();
  return ss.str();
}
std::string corpus(const std::string& n) {
  return std::string(PHOTON_TEST_CORPUS_DIR) + "/convergence/" + n;
}

struct GateProfile {
  int num_qubits = 0;
  int h = 0, x = 0, y = 0, z = 0;
  int s = 0, t = 0;
  int cx = 0, cz = 0, swap = 0;
  int measure = 0;
};

GateProfile profileSpinor(const sd::Module& m) {
  GateProfile p;
  for (const auto& op : m.ops()) {
    using OK = sd::OpKind;
    switch (op.kind) {
      case OK::AllocQubit: ++p.num_qubits; break;
      case OK::H: ++p.h; break;
      case OK::X: ++p.x; break;
      case OK::Y: ++p.y; break;
      case OK::Z: ++p.z; break;
      case OK::S: ++p.s; break;
      case OK::T: ++p.t; break;
      case OK::Cx: ++p.cx; break;
      case OK::Cz: ++p.cz; break;
      case OK::Swap: ++p.swap; break;
      case OK::Measure: ++p.measure; break;
      default: break;
    }
  }
  return p;
}

bool same(const GateProfile& a, const GateProfile& b) {
  return a.num_qubits == b.num_qubits && a.h == b.h && a.x == b.x &&
         a.y == b.y && a.z == b.z && a.s == b.s && a.t == b.t &&
         a.cx == b.cx && a.cz == b.cz && a.swap == b.swap &&
         a.measure == b.measure;
}

CompiledProgram compileFromPho(const std::string& path) {
  auto pr = pl::parse(readFile(path), path);
  if (!pr.module) return {};
  auto lr = pl::lowerToPhonon(*pr.module);
  if (!lr.module) return {};
  return CompiledProgram::fromPhononModule(std::move(*lr.module),
                                           pr.module->target);
}

CompiledProgram compileFromCpp(const std::string& path,
                               const std::string& entry) {
  auto ir = photon::cppfront::ingestCpp(readFile(path), entry, "generic");
  if (!ir.module) return {};
  auto lr = pl::lowerToPhonon(*ir.module);
  if (!lr.module) return {};
  return CompiledProgram::fromPhononModule(std::move(*lr.module),
                                           "generic");
}

}  // namespace

TEST(M6_convergence, bell_pho_vs_cpp) {
  auto a = compileFromPho(corpus("bell.pho"));
  auto b = compileFromCpp(corpus("bell.cpp"), "bell");
  EXPECT_TRUE(a.ok());
  EXPECT_TRUE(b.ok());
  if (!a.ok() || !b.ok()) return;
  auto pA = profileSpinor(*a.spinor());
  auto pB = profileSpinor(*b.spinor());
  EXPECT_EQ(pA.num_qubits, pB.num_qubits);
  EXPECT_EQ(pA.h,  pB.h);
  EXPECT_EQ(pA.cx, pB.cx);
  EXPECT_EQ(pA.measure, pB.measure);
  EXPECT_TRUE(same(pA, pB));
}

TEST(M6_convergence, ghz3_pho_vs_cpp) {
  auto a = compileFromPho(corpus("ghz3.pho"));
  auto b = compileFromCpp(corpus("ghz3.cpp"), "ghz3");
  EXPECT_TRUE(a.ok());
  EXPECT_TRUE(b.ok());
  auto pA = profileSpinor(*a.spinor());
  auto pB = profileSpinor(*b.spinor());
  EXPECT_TRUE(same(pA, pB));
}

TEST(M6_convergence, bell_resource_estimate) {
  auto a = compileFromPho(corpus("bell.pho"));
  auto b = compileFromCpp(corpus("bell.cpp"), "bell");
  EXPECT_TRUE(a.ok());
  EXPECT_TRUE(b.ok());
  auto eA = a.estimate();
  auto eB = b.estimate();
  EXPECT_EQ(static_cast<int>(eA.num_qubits),
            static_cast<int>(eB.num_qubits));
  EXPECT_EQ(static_cast<int>(eA.two_qubit_count),
            static_cast<int>(eB.two_qubit_count));
  EXPECT_EQ(static_cast<int>(eA.t_count),
            static_cast<int>(eB.t_count));
}

SPINOR_TEST_MAIN()
