#!/usr/bin/env python3
"""Submit multiple circuits to IBM hardware via BOTH Spinor and Qiskit
transpilation paths, then print a per-bitstring percentage table
comparing Spinor vs Qiskit vs the theoretical ideal.

Usage:
  python3 submit_suite.py --token ... --instance ... [--backend ibm_fez]
"""
from __future__ import annotations
import argparse
import importlib.util
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
SPINOR_BIN = "/home/ubuntu/heisenberg-research_fullstack-compiler/quantum-stack/build/spinor/cli/spinorc"
REGISTRY = "/home/ubuntu/heisenberg-research_fullstack-compiler/quantum-stack/spinor/registry"

# Each test case lists the circuit name and the ideal distribution
# (dict of bitstring -> probability) computed by hand from theory.
# Bitstring order matches Qiskit's measurement convention: c[0] is
# the rightmost bit. So measuring c[0]=1, c[1]=0 → bitstring '01'.
CASES = [
    {
        "name": "bell",
        "qubits": 2,
        "shots": 1024,
        "olevel": 3,
        "ideal": {"00": 0.5, "11": 0.5, "01": 0.0, "10": 0.0},
        "desc": "Bell pair: 50% |00>, 50% |11>",
    },
    {
        "name": "ghz4",
        "qubits": 4,
        "shots": 1024,
        "olevel": 3,
        "ideal": {"0000": 0.5, "1111": 0.5},
        "desc": "4-qubit GHZ: 50% |0000>, 50% |1111>",
    },
    {
        "name": "grover2",
        "qubits": 2,
        "shots": 1024,
        "olevel": 3,
        "ideal": {"11": 1.0},
        "desc": "2-qubit Grover, target |11>: 100% |11>",
    },
    {
        "name": "grover3",
        "qubits": 3,
        "shots": 1024,
        "olevel": 3,
        "ideal": {"101": 0.781, "000": 0.031, "001": 0.031, "010": 0.031,
                  "011": 0.031, "100": 0.031, "110": 0.031, "111": 0.031},
        "desc": "3-qubit Grover, target |101>: ~78% |101> after 1 iteration",
    },
]


def emit_spinor(name: str, target: str, level: int) -> str:
    """Run `spinorc emit`. With auto-routing, this returns Qiskit
    Python source code for IBM targets (the same code a normal
    Qiskit user would write) — and the legacy native QASM3 for
    non-IBM targets. The caller distinguishes by file content."""
    spn = HERE / "circuits" / f"{name}.spn"
    env = os.environ.copy()
    env["SPINOR_REGISTRY_ROOT"] = REGISTRY
    cmd = [SPINOR_BIN, "emit", "-t", target, "-O", str(level), "-f", "qasm3", str(spn)]
    return subprocess.check_output(cmd, env=env, text=True)


def build_spinor_circuit(name: str, target: str, level: int):
    """Compile via spinorc and produce a Qiskit QuantumCircuit.

    For IBM targets, spinorc emits a self-contained Python program
    with a `build()` function. We import that module and call
    `build()` to get the same QuantumCircuit a normal Qiskit user
    would produce. For non-IBM targets, fall back to parsing the
    emitted native QASM3."""
    out = emit_spinor(name, target, level)
    if out.startswith("# Generated by spinorc"):
        # IBM path: the output is Qiskit Python. Import it and call build().
        import importlib.util, tempfile
        with tempfile.NamedTemporaryFile(
            prefix=f"spinor_emit_{name}_", suffix=".py",
            mode="w", delete=False
        ) as f:
            f.write(out)
            path = f.name
        try:
            spec = importlib.util.spec_from_file_location(f"spnemit_{name}", path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            return mod.build()
        finally:
            os.unlink(path)
    # Non-IBM fallback: parse the QASM3 (uses the existing helper).
    # We don't know the qubit/clbit count from the QASM directly,
    # so look up from the .py file in circuits/.
    qk_qc = qiskit_circuit(name)
    return parse_emitted_qasm(out, qk_qc.num_qubits, qk_qc.num_clbits)


def parse_emitted_qasm(qasm: str, nq: int, nc: int):
    """Build a Qiskit QuantumCircuit from Spinor's emitted QASM."""
    from qiskit import QuantumCircuit
    qc = QuantumCircuit(nq, nc)
    for raw in qasm.splitlines():
        line = raw.strip().rstrip(";")
        if not line or line.startswith(("OPENQASM", "include", "qubit", "bit", "//")):
            continue
        m = re.match(r"c\[(\d+)\]\s*=\s*measure\s+q\[(\d+)\]", line)
        if m:
            qc.measure(int(m.group(2)), int(m.group(1))); continue
        m = re.match(r"(cz|cx|ecr)\s+q\[(\d+)\]\s*,\s*q\[(\d+)\]", line)
        if m:
            getattr(qc, m.group(1))(int(m.group(2)), int(m.group(3))); continue
        m = re.match(r"rz\(([^)]+)\)\s+q\[(\d+)\]", line)
        if m:
            qc.rz(float(m.group(1)), int(m.group(2))); continue
        m = re.match(r"(sx|sxdg|x|y|z|s|sdg|t|tdg|id|h)\s+q\[(\d+)\]", line)
        if m:
            getattr(qc, m.group(1))(int(m.group(2))); continue
    return qc


def qiskit_circuit(name: str):
    p = HERE / "circuits" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"qkc_{name}", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--token", required=True)
    ap.add_argument("--instance", required=True)
    ap.add_argument("--backend", default="ibm_fez")
    args = ap.parse_args()

    from qiskit import transpile
    from qiskit_ibm_runtime import QiskitRuntimeService, SamplerV2

    service = QiskitRuntimeService(channel="ibm_cloud", token=args.token, instance=args.instance)
    backend = service.backend(args.backend)
    print(f"# backend: {args.backend} ({backend.configuration().basis_gates})")
    sampler = SamplerV2(mode=backend)

    submissions = []
    # ----- Submit phase -----
    for case in CASES:
        name = case["name"]
        olevel = case["olevel"]
        print(f"\n# Compiling {name} (-O{olevel})")
        # Qiskit (the reference path).
        qk_qc = qiskit_circuit(name)
        qk_t = transpile(qk_qc, backend=backend, optimization_level=olevel, seed_transpiler=42)
        # Spinor (compile via spinorc, which emits Qiskit Python for
        # IBM targets; we import the generated `build()` and run
        # transpile at the same -O level so the comparison is apples
        # to apples).
        spn_qc = build_spinor_circuit(name, args.backend, olevel)
        spn_t = transpile(spn_qc, backend=backend, optimization_level=olevel, seed_transpiler=42)
        print(f"#   qiskit gates: {dict(qk_t.count_ops())}, depth={qk_t.depth()}")
        print(f"#   spinor gates: {dict(spn_t.count_ops())}, depth={spn_t.depth()}")
        # Submit
        job_q = sampler.run([qk_t], shots=case["shots"])
        job_s = sampler.run([spn_t], shots=case["shots"])
        print(f"#   qiskit job: {job_q.job_id()}")
        print(f"#   spinor job: {job_s.job_id()}")
        submissions.append((case, qk_t, spn_t, job_q, job_s))

    # ----- Wait + collect phase -----
    results = []
    for case, qk_t, spn_t, job_q, job_s in submissions:
        print(f"\n# Waiting for {case['name']}...")
        res_q = job_q.result()
        res_s = job_s.result()
        counts_q = dict(res_q[0].data.c.get_counts())
        counts_s = dict(res_s[0].data.c.get_counts())
        results.append({
            "case": case, "qk_t": qk_t, "spn_t": spn_t,
            "qk_job": job_q.job_id(), "spn_job": job_s.job_id(),
            "counts_q": counts_q, "counts_s": counts_s,
        })

    # ----- Report -----
    print("\n" + "=" * 80)
    print("RESULTS SUMMARY")
    print("=" * 80)
    for r in results:
        c = r["case"]
        print(f"\n## {c['name']} — {c['desc']}")
        print(f"   Qiskit job  {r['qk_job']}  ({dict(r['qk_t'].count_ops())}, depth={r['qk_t'].depth()})")
        print(f"   Spinor job  {r['spn_job']}  ({dict(r['spn_t'].count_ops())}, depth={r['spn_t'].depth()})")
        # Build set of all bitstrings we care about
        keys = set(c["ideal"].keys()) | set(r["counts_q"].keys()) | set(r["counts_s"].keys())
        total = c["shots"]
        # Sort: ideal-mass first, then alphabetical
        sorted_keys = sorted(keys, key=lambda k: (-c["ideal"].get(k, 0), k))
        print(f"   {'bitstring':>10s}  {'ideal%':>8s}  {'qiskit%':>8s}  {'spinor%':>8s}  {'qiskit-Δ':>9s}  {'spinor-Δ':>9s}")
        for k in sorted_keys:
            ideal = c["ideal"].get(k, 0.0) * 100
            qk = r["counts_q"].get(k, 0) / total * 100
            sp = r["counts_s"].get(k, 0) / total * 100
            qk_d = qk - ideal
            sp_d = sp - ideal
            mark = "*" if ideal > 0.1 else " "
            print(f" {mark} {k:>10s}  {ideal:7.2f}%  {qk:7.2f}%  {sp:7.2f}%  {qk_d:+7.2f}pp  {sp_d:+7.2f}pp")
        # Fidelity = total probability on ideal-target bitstrings
        ideal_keys = [k for k, v in c["ideal"].items() if v > 0.5 / 2**c["qubits"]]
        qk_fid = sum(r["counts_q"].get(k, 0) for k in ideal_keys) / total
        sp_fid = sum(r["counts_s"].get(k, 0) for k in ideal_keys) / total
        ideal_fid = sum(v for k, v in c["ideal"].items() if k in ideal_keys)
        print(f"   --> fidelity (sum on ideal targets): qiskit={qk_fid*100:.2f}%  spinor={sp_fid*100:.2f}%  ideal={ideal_fid*100:.2f}%")

    return 0


if __name__ == "__main__":
    sys.exit(main())
