#!/usr/bin/env bash
# scripts/install.sh
#
# One-line install for the Heisenberg CLI binaries (spinorc, photonc,
# phononc). Detects host triple, downloads the correct release tarball
# from the GitHub Pages docs site, verifies provenance via
# `gh attestation verify` (with a SHA256 fallback), and installs to
# ~/.local/heisenberg/ + symlinks into ~/.local/bin/.
#
# Usage:
#   curl -sSL https://nimesh08.github.io/quantum-stack/install.sh | bash
#
# Override release version:
#   curl -sSL .../install.sh | bash -s -- --version v0.1.0
#
# Skip provenance verification (NOT recommended):
#   curl -sSL .../install.sh | bash -s -- --no-verify
set -euo pipefail

VERSION="${HEISENBERG_VERSION:-latest}"
VERIFY=1
PREFIX="${PREFIX:-$HOME/.local}"
INSTALL_DIR="$PREFIX/heisenberg"
BIN_DIR="$PREFIX/bin"
DOCS_BASE="https://nimesh08.github.io/quantum-stack/downloads"
GH_REPO="nimesh08/quantum-stack"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)    VERSION="$2"; shift 2 ;;
    --no-verify)  VERIFY=0;     shift 1 ;;
    --prefix)     PREFIX="$2";  INSTALL_DIR="$PREFIX/heisenberg"; BIN_DIR="$PREFIX/bin"; shift 2 ;;
    -h|--help)
      sed -n '1,/^set -euo/p' "$0" | sed -n 's/^# \?//p' | head -25
      exit 0 ;;
    *) echo "install.sh: unknown flag: $1" >&2; exit 2 ;;
  esac
done

# Detect host triple.
uname_s=$(uname -s 2>/dev/null || echo unknown)
uname_m=$(uname -m 2>/dev/null || echo unknown)
case "$uname_s/$uname_m" in
  Linux/x86_64)  TRIPLE="linux-x86_64" ;;
  Linux/aarch64) TRIPLE="linux-aarch64" ;;
  Linux/arm64)   TRIPLE="linux-aarch64" ;;
  *)
    echo "install.sh: unsupported host: $uname_s/$uname_m" >&2
    echo "Supported: linux-x86_64, linux-aarch64, windows-x86_64 (use install.ps1)" >&2
    exit 1 ;;
esac

echo "host triple: $TRIPLE"
echo "version:     $VERSION"
echo "install:     $INSTALL_DIR"

# Resolve the actual version (latest -> queried via GitHub Releases API).
if [[ "$VERSION" == "latest" ]]; then
  if command -v gh >/dev/null 2>&1; then
    VERSION=$(gh release view --repo "$GH_REPO" --json tagName -q .tagName 2>/dev/null || echo "")
  fi
  if [[ -z "$VERSION" ]]; then
    VERSION=$(curl -sSL "https://api.github.com/repos/$GH_REPO/releases/latest" \
              | grep -oE '"tag_name": *"[^"]+' | head -1 | sed 's/.*"//')
  fi
  if [[ -z "$VERSION" ]]; then
    echo "install.sh: could not resolve 'latest' version" >&2
    exit 1
  fi
  echo "resolved:    $VERSION"
fi

ARTIFACT="heisenberg-cli-$VERSION-$TRIPLE.tar.gz"
URL="$DOCS_BASE/$ARTIFACT"
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

echo "downloading $URL"
curl -fsSL "$URL"          -o "$TMP/$ARTIFACT"
curl -fsSL "$URL.sha256"   -o "$TMP/$ARTIFACT.sha256" || true

# Verify provenance.
if [[ $VERIFY -eq 1 ]]; then
  if command -v gh >/dev/null 2>&1; then
    echo "verifying provenance via gh attestation verify..."
    if gh attestation verify "$TMP/$ARTIFACT" --repo "$GH_REPO"; then
      echo "  ok"
    else
      echo "install.sh: provenance verification FAILED. Aborting." >&2
      exit 1
    fi
  else
    echo "install.sh: 'gh' not found; falling back to SHA256 check"
    if [[ -f "$TMP/$ARTIFACT.sha256" ]]; then
      ( cd "$TMP" && sha256sum -c "$ARTIFACT.sha256" ) \
        || { echo "install.sh: SHA256 mismatch. Aborting." >&2; exit 1; }
    else
      echo "install.sh: no checksum file and no 'gh' to verify provenance." >&2
      echo "install.sh: re-run with --no-verify to skip (NOT recommended)" >&2
      exit 1
    fi
  fi
fi

# Extract.
mkdir -p "$INSTALL_DIR" "$BIN_DIR"
tar -xzf "$TMP/$ARTIFACT" -C "$INSTALL_DIR" --strip-components=1

# Symlink the binaries.
for b in spinorc photonc phononc; do
  src="$INSTALL_DIR/bin/$b"
  if [[ -x "$src" ]]; then
    ln -sf "$src" "$BIN_DIR/$b"
    echo "installed: $BIN_DIR/$b"
  else
    echo "note: $b not found in tarball (skeleton release)" >&2
  fi
done

# Set up the Python entry point. The release ships the spinor_submit
# package directly; we wrap it in a small launcher that prepends the
# bundled python/ to PYTHONPATH. This keeps the install hermetic.
cat > "$BIN_DIR/spinor-submit" <<EOF
#!/usr/bin/env bash
exec python3 -P -c "import sys; sys.path.insert(0, '$INSTALL_DIR/python'); from spinor_submit.__main__ import main; sys.exit(main())" "\$@"
EOF
chmod +x "$BIN_DIR/spinor-submit"
echo "installed: $BIN_DIR/spinor-submit"

# Hint at PYTHONPATH for the C++ binaries' subprocess hop.
ENVRC="$INSTALL_DIR/env.sh"
cat > "$ENVRC" <<EOF
# Generated by install.sh. Source this from your shell:
#   . $ENVRC
export QSTACK_PYTHONPATH="$INSTALL_DIR/python"
export QSTACK_SPINORC="$INSTALL_DIR/bin/spinorc"
EOF
echo "wrote $ENVRC"

# PATH hint.
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo
    echo "Add $BIN_DIR to your PATH:"
    echo "  echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.bashrc"
    ;;
esac

echo
echo "Installed Heisenberg CLI $VERSION ($TRIPLE)."
echo "Try:  spinorc registry list | head"
echo "      photonc version"
echo
echo "For the full provider env-var list:  photonc providers"
